# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.IntegerField(max_length=255)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourists', to='login_app.User')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='login_app.Travel')),
            ],
            managers=[
                ('tripManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
