# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_trip'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='travel',
            managers=[
                ('travelManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date_to',
            field=models.DateTimeField(),
        ),
    ]
