# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20171026_1442'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='travel',
            managers=[
            ],
        ),
    ]
