# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='login_app.Travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tourist',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travel',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
